### ISSUE TITLE
export to libre office - strange codes instead digits and signs

### ISSUE THREAD

**Issue by isannn** [nycdotnet/TSqlFlex#50] opened 2017-03-01 13:27 UTC
i'm used libre office and tried to open result set in scalc.exe. i got _x00xx_ codes instead of special symbols and digits. in ms excel everything worked fine.
ssms result
![2017-03-01_1625](https://cloud.githubusercontent.com/assets/7098911/23461604/a62ae18e-fe9b-11e6-82dc-be6aa1b4f774.png)

scalc.exe result
![2017-03-01_1625_001](https://cloud.githubusercontent.com/assets/7098911/23461633/c0cf85da-fe9b-11e6-9dff-02106582c56d.png)

**Comment by isannn** [comment] 2017-03-02 04:57
video of case: https://www.screencast.com/t/fdG49LcK6
CurrentCulture   : ru-RU
CurrentUICulture : ru-RU
Microsoft SQL Server 2012 (SP3-CU7) (KB3205051) - 11.0.6579.0 (X64) 
collation: Cyrillic_General_CI_AS
libre office scalc setuped as default app for "excel" files
ms excel not installed in system
if i try to "save as" result from scalc - it offers to save as *.xlsx file

**Comment by isannn** [comment] 2017-03-02 05:41
with ms excel it works fine - https://www.screencast.com/t/iJ3kaJ4n4B8

**Comment by nycdotnet** [comment] 2017-03-02 14:58
OK.  Thanks for reporting this, but I believe that the issue you're experiencing is not caused by T-SQL Flex.  Perhaps you have another add-on?  T-SQL Flex only works inside its own window and does not modify the right-click options in SSMS at all.

To get an Excel-compatible sheet from T-SQL Flex, click the T-SQL Flex button in your button bar and paste your query in the top panel, and then select either To XML Spreadsheet or To CSV.  I'm not sure if Libre Office can open the XML Spreadsheet format, but I'm sure it can open CSV and I believe the encoding should be correct to preserve the Cyrillic characters correctly (UTF-8 with BOM).

I will close this as I don't believe it's a T-SQL Flex issue, but please feel free to leave any other comments or questions.  Thanks.

**Closed by nycdotnet** 2017-03-02 14:58 UTC
